/**
 * clean.js — reduce a forwarded school email to just its substance.
 *
 * Run this before any LLM extraction. On the Year 7 "Week 8" bulletin it cuts
 * roughly 40% of tokens, almost all of it signature blocks and repeated
 * Acknowledgement of Country text duplicated at every quote level.
 *
 * Deliberately does NOT strip quoted text. In the Parent Teacher Interview
 * thread the actual commitment ("5.36pm next Wednesday") lives inside a
 * quoted reply. Dropping quotes would lose the answer.
 */

// Lines that are pure boilerplate. Each is tested against the de-quoted line.
const BOILERPLATE = [
  /^in the spirit of reconciliation/i,
  /^we pay our respects to the elders/i,
  /^we extend that respect to all aboriginal/i,
  /^junior school campus\s*\|/i,
  /^middle and senior school campus\s*\|/i,
  /^postal address\s*\|/i,
  /^www\.lindisfarne\.nsw\.edu\.au/i,
  /^cricos no\./i,
  /^this message was automatically generated by seqta/i,
  /^if you think it was sent incorrectly/i,
  /^begin forwarded message:?$/i,
  /^sent from my (iphone|ipad|mobile)/i,
  /^\s*$/,
];

// Empty markdown links left behind by HTML→text conversion: [](https://...)
const EMPTY_LINK = /\[\]\((?:[^)]*)\)/g;

// A signature separator: "-- " on its own line, or "--" followed by a name.
const SIG_SEPARATOR = /^--\s*$/;

/**
 * Strip one level of ">" quote marker and report the depth.
 */
function dequote(line) {
  let depth = 0;
  let rest = line;
  while (/^\s*>\s?/.test(rest)) {
    rest = rest.replace(/^\s*>\s?/, '');
    depth += 1;
  }
  return { depth, text: rest };
}

/**
 * Extract the forwarded-message envelope, if present.
 * Apple Mail emits "*From:* ... *Date:* ... *To:* ... *Subject:* ..."
 * (asterisks) while other clients emit plain "From: ...". Handle both.
 */
export function parseForwardEnvelope(body) {
  const grab = (label) => {
    const re = new RegExp(
      `^\\s*>*\\s*\\*?${label}:\\*?\\s*(.+)$`,
      'im'
    );
    const m = body.match(re);
    return m ? m[1].trim().replace(/\s+/g, ' ') : null;
  };

  const from = grab('From');
  if (!from) return null;

  const emailMatch = from.match(/<([^>]+)>/);

  return {
    originalFrom: from,
    originalFromEmail: emailMatch ? emailMatch[1].toLowerCase() : null,
    originalDate: grab('Date'),
    originalTo: grab('To'),
    originalSubject: grab('Subject')
      ?.replace(/^\*+|\*+$/g, '')
      .replace(/^(?:(?:Re|Fwd|FW):\s*)+/i, '')
      .trim() || null,
  };
}

/**
 * @param {string} raw            plaintextBody from Gmail
 * @param {object} [opts]
 * @param {boolean} [opts.keepQuoteDepth=true]  prefix retained quoted lines
 *                                              with their depth, so the model
 *                                              can tell who said what.
 * @returns {{ text: string, envelope: object|null, droppedLines: number }}
 */
export function cleanEmailBody(raw, opts = {}) {
  const { keepQuoteDepth = true } = opts;
  if (!raw) return { text: '', envelope: null, droppedLines: 0 };

  const envelope = parseForwardEnvelope(raw);

  const lines = raw
    .replace(/\uFEFF/g, '')          // zero-width no-break space, all over Apple Mail
    .replace(EMPTY_LINK, '')
    .replace(/\r\n/g, '\n')
    .split('\n');

  const out = [];
  let dropped = 0;
  // Once we hit a signature separator at a given quote depth, drop the rest
  // of that depth's content.
  const sigDepth = new Set();

  for (const line of lines) {
    const { depth, text } = dequote(line);
    const trimmed = text.trim();

    if (SIG_SEPARATOR.test(trimmed)) {
      sigDepth.add(depth);
      dropped += 1;
      continue;
    }
    if (sigDepth.has(depth) && trimmed !== '') {
      // Still inside a signature at this depth. Allow escape if we clearly
      // re-enter prose (a long sentence), otherwise keep dropping.
      if (trimmed.length < 120) {
        dropped += 1;
        continue;
      }
      sigDepth.delete(depth);
    }

    if (BOILERPLATE.some((re) => re.test(trimmed))) {
      dropped += 1;
      continue;
    }

    // Envelope headers are captured separately; don't repeat them inline.
    if (/^\*?(?:From|Date|To|Cc|Subject|Reply-To):\*?/i.test(trimmed)) {
      dropped += 1;
      continue;
    }

    const prefix = keepQuoteDepth && depth > 0 ? `[q${depth}] ` : '';
    out.push(prefix + trimmed);
  }

  // Collapse runs of blank lines.
  const text = out
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return { text, envelope, droppedLines: dropped };
}
