/**
 * seqta.js — deterministic parser for SEQTA Teach machine mail.
 *
 * These messages are template-generated and never vary in shape, so they need
 * no LLM. Parsing them here is free, instant, and cannot hallucinate.
 *
 * Confirmed live shape (9 Sep 2026):
 *
 *   Subject: [TA:PC] Commendation entered for Rose Howsam (7, 7H, ANDR, ML)
 *
 *   ###############################################################...
 *   Commendation entered for Rose Howsam (7, 7H, ANDR, ML)
 *   ###############################################################...
 *
 *   Entered by: Ms Karissa Wortmann
 *   Subcategory: Lindisfarne Values and Culture
 *   From: September 9, 2026 8:33:47 AM
 *   Until:
 *   Points:
 *
 *   ---------------------------------------------------------------...
 *   This message was automatically generated by SEQTA Teach.
 *
 * IMPORTANT: `From` and `Until` are the pastoral record's validity window.
 * They are NOT event times. They are deliberately named recordFrom /
 * recordUntil here so nothing downstream can mistake them for a start time.
 */

const SCHOOL_TZ = 'Australia/Sydney';

/**
 * Subject line. Tolerates any stack of Fwd:/FW:/Re: prefixes, which forwarded
 * mail always carries.
 *
 * Captures: tag ("PC"), action ("Commendation entered"), student name,
 * and the parenthesised code block.
 */
const SUBJECT_RE =
  /^(?:(?:Fwd|FW|Re|RE|AW|TR)\s*:\s*)*\[TA:(?<tag>[A-Z]{1,6})\]\s*(?<action>.+?)\s+for\s+(?<student>[^(]+?)\s*\((?<codes>[^)]*)\)\s*$/;

/**
 * Body field labels, in the order SEQTA emits them. All may be empty.
 * Matched at line start so a colon inside prose can't trigger a false field.
 */
const FIELD_LABELS = ['Entered by', 'Subcategory', 'From', 'Until', 'Points'];

const MONTHS = {
  january: 1, february: 2, march: 3, april: 4, may: 5, june: 6,
  july: 7, august: 8, september: 9, october: 10, november: 11, december: 12,
};

/**
 * Codes in the subject parens, positionally:
 *   (7, 7H, ANDR, ML)
 *    ^  ^    ^     ^
 *    |  |    |     campus
 *    |  |    house
 *    |  class / form group
 *    year level
 *
 * `house` and `campus` are inferred from position and are NOT yet verified —
 * ML is almost certainly Mahers Lane (Middle & Senior campus) and ANDR a house
 * name, but confirm both against a real second example before relying on them.
 * Unknown codes pass through verbatim rather than being dropped.
 */
export const CODE_MAP = {
  campus: {
    ML: 'Mahers Lane',
    SA: 'Sunshine Avenue',
  },
  house: {
    // ANDR: 'Andrews',   // <- confirm before enabling
  },
};

/**
 * Display eligibility. DEFAULT IS DENY.
 *
 * SEQTA sends positive and negative pastoral records down the same pipe. The
 * fridge is a shared surface visible to siblings and visitors, so anything not
 * explicitly allowed here routes to adult devices only.
 *
 * Extend deliberately, one confirmed subcategory at a time.
 */
const DISPLAY_ALLOW = [
  { action: /^commendation\b/i, subcategory: /^lindisfarne values and culture$/i },
  { action: /^commendation\b/i, subcategory: /^academic\b/i },
];

/** How long a positive record stays on the fridge before it ages out. */
export const DISPLAY_TTL_DAYS = 5;

function offsetMs(date, timeZone) {
  const dtf = new Intl.DateTimeFormat('en-US', {
    timeZone,
    hour12: false,
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
  });
  const p = Object.fromEntries(dtf.formatToParts(date).map((x) => [x.type, x.value]));
  const asUTC = Date.UTC(+p.year, +p.month - 1, +p.day, +p.hour % 24, +p.minute, +p.second);
  return asUTC - date.getTime();
}

/** Convert wall-clock components in `timeZone` to a correct UTC Date. */
function zonedToUtc(y, mo, d, h, mi, s, timeZone) {
  const naive = Date.UTC(y, mo - 1, d, h, mi, s);
  let ts = naive;
  for (let i = 0; i < 2; i += 1) {
    ts = naive - offsetMs(new Date(ts), timeZone);
  }
  return new Date(ts);
}

/**
 * Parse SEQTA's date format: "September 9, 2026 8:33:47 AM"
 * Interpreted as school-local time, returned as UTC.
 */
export function parseSeqtaDate(value, timeZone = SCHOOL_TZ) {
  if (!value) return null;
  const m = value
    .trim()
    .match(
      /^([A-Za-z]+)\s+(\d{1,2}),\s*(\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?)?$/i
    );
  if (!m) return null;

  const month = MONTHS[m[1].toLowerCase()];
  if (!month) return null;

  const day = +m[2];
  const year = +m[3];
  let hour = m[4] ? +m[4] : 0;
  const minute = m[5] ? +m[5] : 0;
  const second = m[6] ? +m[6] : 0;
  const meridiem = m[7]?.toUpperCase();

  if (meridiem === 'PM' && hour < 12) hour += 12;
  if (meridiem === 'AM' && hour === 12) hour = 0;

  return zonedToUtc(year, month, day, hour, minute, second, timeZone);
}

function parseFields(body) {
  const fields = {};
  const lines = body.split('\n');

  for (const line of lines) {
    const stripped = line.replace(/^\s*>\s?/g, '').trim();
    for (const label of FIELD_LABELS) {
      const re = new RegExp(`^${label}\\s*:\\s*(.*)$`, 'i');
      const m = stripped.match(re);
      if (m) {
        const val = m[1].trim();
        fields[label] = val === '' ? null : val;
      }
    }
  }
  return fields;
}

/**
 * Everything between the ### banner and the first "Label:" line is the
 * narrative body — the teacher's actual comment. This is the bit worth
 * putting on the fridge.
 */
function parseNarrative(body, headline) {
  const clean = body.replace(/^\s*>\s?/gm, '');

  // Drop the hash banner and the repeated headline inside it.
  let text = clean
    .replace(/^#{10,}\s*$/gm, '')
    .replace(/^-{10,}\s*$/gm, '');

  if (headline) {
    text = text.replace(headline, '');
  }

  // Cut at the first field label.
  const cutRe = new RegExp(`^(?:${FIELD_LABELS.join('|')})\\s*:`, 'im');
  const cut = text.search(cutRe);
  if (cut > -1) text = text.slice(0, cut);

  // Also cut the SEQTA footer if the fields were absent.
  text = text.split(/This message was automatically generated/i)[0];

  return text.replace(/\n{2,}/g, '\n').trim() || null;
}

function isDisplayEligible(action, subcategory) {
  if (!action) return false;
  return DISPLAY_ALLOW.some(
    (rule) =>
      rule.action.test(action) &&
      (!rule.subcategory || (subcategory && rule.subcategory.test(subcategory)))
  );
}

/**
 * @param {object} message  { subject, plaintextBody, date, sender }
 * @returns {object|null}   null if this isn't SEQTA mail — caller should then
 *                          fall through to the LLM extractor.
 */
export function parseSeqtaMessage(message) {
  const { subject = '', plaintextBody = '', date = null, sender = null } = message;

  const sm = subject.match(SUBJECT_RE);
  if (!sm) return null;

  const { tag, action, student, codes } = sm.groups;
  const parts = codes.split(',').map((c) => c.trim()).filter(Boolean);
  const [yearLevel, className, houseCode, campusCode] = parts;

  const fields = parseFields(plaintextBody);
  const headline = `${action} for ${student} (${codes})`;

  const subcategory = fields.Subcategory ?? null;

  return {
    source: 'seqta',
    tag,                                   // "PC" = pastoral care
    action: action.trim(),                 // "Commendation entered"
    kind: /commendation/i.test(action) ? 'commendation' : 'pastoral_record',

    student: student.trim(),
    person: student.trim().split(/\s+/)[0], // "Rose" — matches calendar convention
    yearLevel: yearLevel ?? null,
    className: className ?? null,
    house: CODE_MAP.house[houseCode] ?? houseCode ?? null,
    campus: CODE_MAP.campus[campusCode] ?? campusCode ?? null,

    enteredBy: fields['Entered by'] ?? null,
    subcategory,
    points: fields.Points ? Number(fields.Points) : null,

    // Record validity window. NOT an event time.
    recordFrom: parseSeqtaDate(fields.From),
    recordUntil: parseSeqtaDate(fields.Until),

    narrative: parseNarrative(plaintextBody, headline),

    receivedAt: date ? new Date(date) : null,
    senderEmail: sender,

    // Routing
    displayEligible: isDisplayEligible(action, subcategory),
    displayTtlDays: DISPLAY_TTL_DAYS,
    needsReview: !isDisplayEligible(action, subcategory),

    // Never an event. Keeps the discriminator honest downstream.
    isEvent: false,
    confidence: 1.0,
  };
}

/** Cheap pre-check so the router can branch without full parsing. */
export function isSeqtaSubject(subject = '') {
  return SUBJECT_RE.test(subject);
}
