import { parseSeqtaMessage, isSeqtaSubject, parseSeqtaDate } from './lib/ingest/seqta.js';
import { cleanEmailBody } from './lib/ingest/clean.js';
import { buildPrompt, dedupeAgainstCalendar } from './lib/ingest/bulletin.js';

// ── Real message 1: SEQTA commendation (direct, auto-forwarded) ────────────
const seqtaMsg = {
  subject: '[TA:PC] Commendation entered for Rose Howsam (7, 7H, ANDR, ML)',
  sender: 'karissa.wortmann@lindisfarne.nsw.edu.au',
  date: '2026-09-09T01:06:17Z',
  plaintextBody: `###############################################################################
Commendation entered for Rose Howsam (7, 7H, ANDR, ML)
###############################################################################

Entered by: Ms Karissa Wortmann

Subcategory: Lindisfarne Values and Culture

From: September 9, 2026 8:33:47 AM

Until:

Points:

-------------------------------------------------------------------------------

This message was automatically generated by SEQTA Teach.
If you think it was sent incorrectly, please contact your school's IT department.`,
};

// ── Real message 2: same, but manually forwarded, for Tom ──────────────────
const seqtaFwd = {
  subject: 'Fwd: [TA:PC] Commendation entered for Tom Howsam (6, 6C, ANDR, ML)',
  sender: 'matthowsam@me.com',
  date: '2026-09-09T01:58:52Z',
  plaintextBody: seqtaMsg.plaintextBody.replace('Rose Howsam (7, 7H', 'Tom Howsam (6, 6C'),
};

console.log('=== SEQTA: direct ===');
console.log(JSON.stringify(parseSeqtaMessage(seqtaMsg), null, 2));

console.log('\n=== SEQTA: forwarded (Tom) ===');
const tom = parseSeqtaMessage(seqtaFwd);
console.log(JSON.stringify({
  person: tom.person, yearLevel: tom.yearLevel, className: tom.className,
  campus: tom.campus, displayEligible: tom.displayEligible,
  recordFrom: tom.recordFrom?.toISOString(),
}, null, 2));

console.log('\n=== Date parse (school local -> UTC) ===');
console.log('Sep  9 8:33:47 AM  ->', parseSeqtaDate('September 9, 2026 8:33:47 AM')?.toISOString(), '(AEST +10)');
console.log('Nov 12 8:33:47 AM  ->', parseSeqtaDate('November 12, 2026 8:33:47 AM')?.toISOString(), '(AEDT +11)');

console.log('\n=== Non-SEQTA subject falls through ===');
console.log('isSeqtaSubject("Fwd: Week 8") =', isSeqtaSubject('Fwd: Week 8'));
console.log('parseSeqtaMessage returns    =', parseSeqtaMessage({ subject: 'Fwd: Week 8', plaintextBody: '' }));

// ── Real message 3: the Week 8 bulletin ───────────────────────────────────
const week8 = `Matt Howsam

Begin forwarded message:

> From: Mr D Hodgetts <daniel.hodgetts@lindisfarne.nsw.edu.au>
> Date: 6 September 2026 at 5:02:25 pm AEST
> To: matthowsam@me.com
> Subject: Week 8
> Reply-To: Mr D Hodgetts <daniel.hodgetts@lindisfarne.nsw.edu.au>
>
> \ufeff
>
> G'day Everyone,
> Welcome to Week 8! We hope all of our Dads and father figures in the Year 7 community had a wonderful Father's Day over the weekend.
> Here is an overview of key assessment dates, upcoming events, and student activities for Year 7 in the week ahead.
> Key Updates & Events
> Year 7 Assessments
> Monday, 7 September: Science Assessment (Task 3).
> Support & Tracking: Please reach out directly to subject teachers if you or your child have any questions regarding assessment tasks. As Weeks 8, 9, and 10 remain a busy period for assessments, we encourage checking in at home to see how things are going. Detailed assessment tasks, due dates, and criteria are visible on SEQTA.
> Sing for R U OK? Day & School Events
> R U OK? Day (Friday, 11 September): On Friday, students are encouraged to engage in discussions around the importance of mental health and asking "R U OK?".
> Volleyball Match: Students vs. Staff Volleyball in NGAH at 12:45 PM - 1:25 PM on Friday, 11 September.
> Big Boys' Breakfast: Dads, Grandparents, and special friends are invited on Thursday, 10 September at 7:30 AM - 8:15 AM on the Senior Centre Deck (Mahers Lane).
> Parent-Teacher Interviews
> Stage 4 & 5 Parent-Teacher Evening: Tuesday, 8 September, from 4:00 PM - 8:00 PM in NGAH.
> Middle School Wellbeing Week
> Alongside R U OK? Day, Middle School students will participate in daily activities framed around the PERMA model for positive psychology:
> Day 1 - Positive Emotion (P): Positivity Routine - Partner warm-up sharing small wins, the "3 Good Things Challenge" recorded on sticky notes, and building a classroom Positivity Wall.
> Day 2 - Engagement (E): Strengths Routine - Reflecting on state-of-flow experiences, taking the Superpower Survey.
> As always, if you have any questions, please reach out to us or your child's teachers.
> Regards
>
> Daniel and Catherine

--
Lisa Price
Teacher

In the spirit of reconciliation, we acknowledge the Traditional Owners and Custodians of the Land on which we live, play, learn, and work.

We pay our respects to the Elders of the Bundjalung Country, past, present, and emerging.
Junior School Campus | Sunshine Avenue | TWEED HEADS SOUTH NSW 2486
www.lindisfarne.nsw.edu.au | CRICOS No. 03803G`;

const cleaned = cleanEmailBody(week8);
console.log('\n=== Cleaner on Week 8 bulletin ===');
console.log('original chars :', week8.length);
console.log('cleaned chars  :', cleaned.text.length);
console.log('reduction      :', Math.round((1 - cleaned.text.length / week8.length) * 100) + '%');
console.log('envelope       :', JSON.stringify(cleaned.envelope, null, 2));

// ── Dedupe against the real Home calendar ─────────────────────────────────
const proposed = [
  { title: 'Science Assessment (Task 3)', person: 'Rose', date: '2026-09-07' },
  { title: 'Big Boys Breakfast',          person: 'Rose', date: '2026-09-10' },
  { title: 'Students vs Staff Volleyball',person: 'Rose', date: '2026-09-11' },
  { title: 'Mufti Day',                   person: 'household', date: '2026-09-09' },
];

const homeCalendar = [
  { summary: 'Mufti Day - gold coin', start: { date: '2026-09-09' } },
  { summary: 'Rose PE Prac',          start: { date: '2026-09-10' } },
  { summary: 'Tom Surfing',           start: { dateTime: '2026-09-10T16:00:00+10:00' } },
];

console.log('\n=== Dedupe against Home calendar ===');
for (const r of dedupeAgainstCalendar(proposed, homeCalendar)) {
  console.log(
    `${r.needsReview ? 'PROPOSE ' : 'SUPPRESS'}  ${r.date}  ${r.title}` +
    (r.duplicateOf ? `   (already on calendar)` : '')
  );
}

console.log('\n=== Prompt size ===');
const prompt = buildPrompt({
  body: cleaned.text,
  subject: 'Fwd: Week 8',
  receivedAt: '2026-09-06T07:02:25Z',
  sender: 'daniel.hodgetts@lindisfarne.nsw.edu.au',
});
console.log('prompt chars   :', prompt.length, `(~${Math.round(prompt.length / 4)} tokens)`);
